import = ["/Users/rabrennie/.config/alacritty/catppuccin-frappe.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "JetbrainsMono NF"

[window]
decorations = "none"

[window.padding]
x = 16
y = 16
