"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory \
$git_branch \
$ruby \
$nodejs \
$fill \
$time \
$line_break\
$character"""

add_newline = true

[directory]
truncation_length = 4
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style)"
style = 'cyan'

[character]
success_symbol = '[➜](green)'

[git_branch]
symbol = ' '
format = '[//](dimmed) [$symbol($branch)]($style)'
style = "purple"

[time]
disabled = false

[fill]
symbol = ' '
style = 'bold green'

[ruby]
symbol = " "
format = "[//](dimmed) [$symbol($version)]($style)"
style = 'red'
detect_variables = []

[nodejs]
symbol = " "
format = "[//](dimmed) [$symbol($version)]($style)"
style = "green"
